### ISSUE TITLE
PFQuery's whereKey:equalTo: function seems not working on Parse Server like before

### ISSUE THREAD

**Issue by leobortolotti** [ParsePlatform/parse-server#175]
Hi,
Inside Parse I have a key where I store an array of Pointers. Then I use the PFQuery's function whereKey:equalTo: like this:
`[query whereKey:@"members" equalTo:[PFUser currentUser]];`
The problem is that when it was Parse hosted, it was working well. But now with Parse Server it isn't working. It isn't retrieving the objects from Class that have [PFUser currentUser] inside the key's array.
Is it a bug in Parse Server?

**Comment by leobortolotti** [comment]
The solution that I found is to use:
`[query whereKey:@"members" containsAllObjectsInArray:@[[PFUser currentUser]]];`
Works fine!!

**Comment by mkll** [comment]
> The problem is that when it was Parse hosted, it was working well

But it should not. Array of objects can't be equal to object.

**Comment by leobortolotti** [comment]
See the answer of Héctor Ramos from Parse at this link:
[](https://parse.com/questions/query-where-the-elements-of-an-array-type-field-are-a-subset-of-a-given-array)

**Comment by mkll** [comment]
Ok, I was wrong, got it. But I can not call it good practice.

**Comment by leobortolotti** [comment]
I agree with you. An array of objects can't be equal to object.
It would be better with a new function for this case...

**Comment by edvincandon** [comment]
Hey @leobortolotti , this was reported as a bug as I noticed the same strange behaviour. #74 
I worked around this (for now), by storing only the object id's in an array.. You'll have to refactor some of your code, but works just fine with an array of id's.

**Comment by leobortolotti** [comment]
@edvincandon Got it. As I said, I found this solution too:
`[query whereKey:@"members" containsAllObjectsInArray:@[[PFUser currentUser]]];`
But what you said is a good alternative too!! Thanks!

**Comment by drew-gross** [comment]
This has been fixed in #284

**Comment by aoguzhan** [comment]
hey, i have 2.0.8 installed but it seems still not fixed. 

this is my query:

` [query whereKey:@"bikers" equalTo:[PFUser currentUser]];`

this is how data stored in db:

```
"bikers" : [ 
        {
            "__type" : "Pointer",
            "className" : "_User",
            "objectId" : "s6pjE71Hqk"
        }, 
        {
            "__type" : "Pointer",
            "className" : "_User",
            "objectId" : "27eJDbeT96"
        }
    ],
```
but it works with:

`[query whereKey:@"bikers" containsAllObjectsInArray:@[[PFUser currentUser]]];`

did i miss something?

**Comment by kenkuan** [comment]
Hi, @drew-gross 

Recently, I tried to migrate my app to parse-server and met this issue.

My parse-server version is `2.2.10` which this issue should be fixed.

I have a class called `Room` which has an array field `members`.

I tried 

 `q.equalTo("members", PFUser.currentUser())` 

returned nothing, but with 

`q.whereKey("members", containsAllObjectsInArray:[PFUser.currentUser])`

 it worked.

I checked my `_Scheme` and it marked `room.members` as an array. 

Is there any idea why this issue still exist?

**Comment by richardgroves** [comment]
I'm seeing the same as @alioguzhan  and @kenkuan. Am using a hosted Parse server of version 2.2.19, calling from iOS SDK v.1.14.2 (from cocoapods)

and a query that worked against the original Parse service no longer works.

Key 'userAck' has a value of `[{"__type":"Pointer","className":"UserPublicData","objectId":"hkZD66uTV1"}]`

and before a query of:
`[query whereKey:@"userAck" equalTo:publicUser];`
where 'publicUser' is an object of type UserPublicData, worked fine.

Now it gets 0 matches and I have to change it to 
`[query whereKey:@"userAck" containsAllObjectsInArray:@[publicUser]];`
to get any results.

And while the revised syntax does make more sense it means I've got an unknown about of broken queries throughout my code base, and previously documented behaviour has changed.

The above reported fix https://github.com/ParsePlatform/parse-server/pull/284 does not seem to have worked for several of us.

**Comment by hackin247** [comment]
Has this been resolved?   I'm just now running into this issue via JS query.equalTo()
