### ISSUE TITLE
schema mismatch for _Session.user; expected Pointer but got String

### ISSUE THREAD

**Issue by GrandAyrat** [ParsePlatform/parse-server#2068]
When i call from JS client newUser.signUp i have error: schema mismatch for _Session.user; expected Pointer but got String

**Comment by drew-gross** [comment]
Can you make sure you are on the latest version of Parse Server? This issue should be fixed already.

**Comment by csujedihy** [comment]
I have the same problem. Just downgrade deepcopy to v0.61.

**Comment by valero90** [comment]
Same problem to me with parse-server version 2.2.13 using the Parse JavaScript SDK. 
@csujedihy if I downgraded deepcopy to v0.61 and with parse-server in v2.2.13 it's still not working.

**Comment by codebreach** [comment]
I had the same error but it worked on v2.2.13

**Comment by flovilmart** [comment]
Closing due to lack of activity, please update to latest parse-server version and reopen if the issue persist.

Don't forget to include your current:
- node version
- npm version
- parse-server version
- any relevant logs (VERBOSE=1 will enable verbose logging)
