### ISSUE TITLE
Horrible response times

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#2556]
Please read the following instructions carefully.

Check out https://github.com/ParsePlatform/parse-server/issues/1271 for an ideal bug report. 
The closer your issue report is to that one, the more likely we are to be able to help, and the more likely we will be to fix the issue quickly!

Many members of the community use Stack Overflow and Server Fault to ask questions. 
Read through the existing questions or ask your own!
- Stack Overflow: http://stackoverflow.com/questions/tagged/parse.com 
- Server Fault: https://serverfault.com/tags/parse

For database migration help, please file a bug report at https://parse.com/help#report

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [ x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x ] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x ] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x ] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

We are testing out a heroku standard server along with mlab m1 cluster, both servers are in the same region.  I installed new relic monitoring tools to see how the server would handle just a few users, maybe 5-9 and deff not at the same time.  Looking at response times returns its pretty crazy to see 1 to 2 second response times ..

Here is a transaction trace from NR

![image](https://cloud.githubusercontent.com/assets/519563/17818805/f11f16fa-65f9-11e6-97b3-74f274647e22.png)

![image](https://cloud.githubusercontent.com/assets/519563/17818843/150cdcc8-65fa-11e6-99b0-7bccff80e351.png)

Describe your issue in as much detail as possible.

No idea how to debug this or see whats causing this huge hang in response times.

### Steps to reproduce

Would need our data set and app, but can provide access to a parse dev.

#### Expected Results

better response times.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.17
  - Operating System:     Heroku Standar Dyno
  - Hardware:             Heroku Standar Dyno
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version:3.2
  - Storage engine:  wiredtirger
  - Hardware:        Mlab M1 server 1.7 gig of ram clustered.
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

nothing really in here

**Comment by nirco123** [comment]
I am having the same issues, all started when from version from 2.2.23, I suspect that the issue somehow relate to the user side of each request.

**Comment by flovilmart** [comment]
@nirco123 Are you seeing it as well on you local development machine with a local mongodb?

**Comment by jeveloper** [comment]
I see periodical spikes , regular latency against my cloud code is about 200-300ms and then once in a while 1.9 seconds or so

**Comment by acinader** [comment]
Not exactly on topic, but is there a recommended profiling tool?  I'd like to start sampling but not sure what the state of the art is on this stack.

**Comment by gateway** [comment]
I going to roll back to 2.2.15, some people said anything > than that are seeing potential issues.  I havent had time to debug it but have some profiling tools running over the weekend, I agree to seeing the spikes that @jeveloper is seeing as well.

**Comment by jeveloper** [comment]
I assumed that its the cached object tree that gets flushed x amount of seconds, not entirely sure, but i suspect that its flushing EVERYTHING regardless of update frequency or TTYL.

if anyone is using custom cache adaptor, id love to hear

**Comment by gateway** [comment]
So Im using app dynamics to dig though some of these long requests.. Here is an image of a call that took 868ms

![image](https://cloud.githubusercontent.com/assets/519563/17866226/98cabe74-685a-11e6-9a3d-91a7b9ef082d.png)

those calls alone add up to 250ms..  stringify seems expensive, then 2 calls to SchemaController ?

**Comment by gateway** [comment]
Here is an hour snapshot , you can see quite a bit of slow responses happening.. :( 

![image](https://cloud.githubusercontent.com/assets/519563/17866709/66f40426-685c-11e6-9c27-2f2e08d6d980.png)

**Comment by gateway** [comment]
So to provide more details for example.

We have a banner class which has the following:

Start and End Date for the banner (string)
Name of the Banner (string)
Banner ID (link to s3 image)
LocationID (our location data ID - string)
Radius (string)
Disabled (Number)

Our iOS client does a query around a geoPoint to see if the user is in an area where a banner would show up.

iOS Swift Function.

```
class func queryForAdsToDisplay(userGeo:PFGeoPoint, complete: (result: [Banners]) -> Void) {

      let query = PFQuery(className: "Banners")
      query.whereKey("disabled", notEqualTo: 1)
      query.whereKey("geoPoint", nearGeoPoint: userGeo, withinMiles: 20)

      query.findObjectsInBackgroundWithBlock { (objects, error) in

         if error == nil {

            var dataToExtract = [Banners]()

            if objects != nil {

               for aBanner in objects! {

                  dataToExtract.append(aBanner as! Banners)
               }

               complete(result: dataToExtract)
            }

         } else {

            // Log details of the failure
            print("Error@@@@: \(error!) \(error!.userInfo)")
         }
      }
   }
```

We have no cloud code for this function..

Here is an example of what we are seeing under the hood from the tools we are using.

![image](https://cloud.githubusercontent.com/assets/519563/17868488/e3c1a04c-6863-11e6-8ec4-adc704f24eca.png)

For this specific call it was 1,535 ms ..

The call graph for this class seems to have spent 61% in the auth/scram.jj line 75

![image](https://cloud.githubusercontent.com/assets/519563/17868709/d75770ec-6864-11e6-83d2-08aedf197e31.png)

![image](https://cloud.githubusercontent.com/assets/519563/17868779/21128abe-6865-11e6-9934-e5516c4b76a2.png)


This is the index for the db, please understand im getting used to figuring out how to set indexe's up since parse.com did it all for us.

![image](https://cloud.githubusercontent.com/assets/519563/17868596/557817ac-6864-11e6-9d66-cd65bbc7c648.png)

I should also make a note its not just this class.

**Comment by flovilmart** [comment]
The auth/scram look to be part of the mongo driver. Not sure what we can do about it now. Maybe you should ask the guys at MongoDB about that module.

**Comment by gateway** [comment]
@flovilmart let me call them right up :) this is not the only issue, again as stated 50% of the classes are having high response times :(

**Comment by jeveloper** [comment]
I read a bit about this @gateway  , it might be that we're sending different salts and scram has to do its check, that could be the problem. Are you running mongodb 3.0 (with or without rocksdb) or mongo 3.2? I wonder if its possible to tune this.

I suspect parse server is not reusing connections to mongodb and establishing new ones every time with user/pwd for every call

**Comment by gateway** [comment]
@jeveloper running 3.2 , I might fire up a 3.0 but I prefer to get 3.2 with WiredTiger running for the performance increase and space reduction.

**Comment by flovilmart** [comment]
Should we close that one as it seems this has been resolved offline?

**Comment by jeveloper** [comment]
Hey @flovilmart @gateway  , please don't close, its still an issue for many of us.
As i mentioned : "I suspect parse server is not reusing connections to mongodb and establishing new ones every time with user/pwd for every call"  , shouldnt the server (parse) contain a connection pool to avoid auth every time an api is called? 
each time we use mongodb connect() , thats a new connection and scram is used, cpu spike and delays.

Any ideas how to mitigate this ? That would be great.

**Comment by flovilmart** [comment]
@jeveloper I don't see this issue, the mongo is connected once and for all, until the connection hits a timeout, If you application receive little traffic, or that your connection timeout is too low, the connection will be close by the mongo driver.

**Comment by steven-supersolid** [comment]
@gateway if it was solved offline, could you share the solution for the benefit of others?

**Comment by flovilmart** [comment]
> I suspect parse server is not reusing connections to mongodb and establishing new ones every time with user/pwd for every call

If a new connection is established for every calls this is not parse-server as we maintain one connection (that is a pool, managed by the mongodb driver). When that connection is closed, failed, we mark it so the next time a request come, a new connection is established.

**Comment by jeveloper** [comment]
Thanks! I did some digging, saw that too. 
@flovilmart  is there a way to control cache data (ttyl and all) ? I feel like its very short

**Comment by flovilmart** [comment]
This Would be into your driver settings, they can be updated through the URL you pass for the DB.

**Comment by jeveloper** [comment]
@flovilmart sorry i meant parse-server configuration for caching data, perhaps using redis

**Comment by flovilmart** [comment]
This is deviating from the original issue.

This is not part of parse-server, but pull requests are welcome, as always.

**Comment by gateway** [comment]
So, this is not resolved, their was really no solution. I did have a few things happening at the same time but with those gone im still seeing various spikes.

We dont have much traffic right now just a few beta testers fyi so its not like the server is being bombarded.

I still have no idea what Middleware: anon is, if we could drill down into this we might be able to see what is going on.  

![image](https://cloud.githubusercontent.com/assets/519563/17978793/8d97b008-6aac-11e6-8c37-d7ad936050e4.png)

Also, I need to rehook up the app dynamics I was using that gave me a tiny bit more info.  

@flovilmart him and I have talked off of this issue, and he has been awesome at providing me some help/feedback for parse, how ever we all have different environments set up, different code running so one person in a test environment might not see these issues but when people start to use parse more and more I'm assuming this will crop up.  Its just how to debug this is the bigger concern.

Here is a big spike seems like in Request Queuing

![image](https://cloud.githubusercontent.com/assets/519563/17978903/04b75274-6aad-11e6-8462-34448e7fd51a.png)

and well hear is new relics break down, again cant drill down to the code, and I plan on getting that set up because we are prepping for launch soon :/

![image](https://cloud.githubusercontent.com/assets/519563/17979073/bd719be4-6aad-11e6-9847-c58734fe1a3e.png)

**Comment by flovilmart** [comment]
> I still have no idea what Middleware: anon is

The middleware: anon is likely to be the anonymous function that runs to process your request i.e.: parse-server...

If you have not much traffic, this is probably the driver reconnecting...

Look at the mongo doc here: https://docs.mongodb.com/manual/reference/connection-string/#connection-options

Try setting the socketTimeoutMS to a large value like 1000 * 60 (1 minute). 

Looks also in mongodb logging http://mongodb.github.io/node-mongodb-native/2.2/reference/management/logging/ to enable some verbose logs on your development systems to make sure mongo is not reconnecting or blocking.

**Comment by gateway** [comment]
@flovilmart reaching out to Mlab right now to see if they can shed some light on this.

**Comment by flovilmart** [comment]
So everything is fine, 87% of your requests are normal...

**Comment by rogernolan** [comment]
> 87% of your requests are normal

That doesn't sound fine to me considering the low load we're talking about.

**Comment by jeveloper** [comment]
FYI running mongodb (with Rocks mind you) righta long parse-server doesn't make it any faster.

**Comment by flovilmart** [comment]
Did you try increasing the socket timeout on the MongoDB driver?

**Comment by rogernolan** [comment]
Doesn't Parse set socket timeout on the MongoDB to 30s by default?

**Comment by flovilmart** [comment]
You can set it right into the MongoDB URI

**Comment by jeveloper** [comment]
@gateway curious if you tried that in your configuration 
by the way that App dynamics looks amazing, are you on a paid plan to see all this crazy insight?
