### ISSUE TITLE
Cannot update _User, _Role, _Product, _Installation, _Session via Schemas API

### ISSUE THREAD

**Issue by ntloc592** [ParsePlatform/parse-server#804]
- When I try to update _User, _Role, _Product, _Installation, _Session via Schemas API

- Result:
{
    "code": 136,
    "error": "field 'field name....' cannot be added"
}

**Comment by drew-gross** [comment]
This should be fixed by #797

**Comment by Marco129** [comment]
@drew-gross #797 did not fix this bug.
Perhaps is another problem in function `buildMergedSchemaObject `of Schema.js

**Comment by drew-gross** [comment]
OK, thanks for the heads up. Reopening.

**Comment by drew-gross** [comment]
Merged #811

**Comment by ntloc592** [comment]
I try to update system scheme with lasted version, but I can not do that

- var sysSchemaField = Object.keys(defaultColumns).indexOf(mongoObject._id) === -1 ? [] : Object.keys(defaultColumns[mongoObject._id]);

- This is not working with System schema.
- mongoObject._id is alway 'undefined', so sysSchemaField is alway []

**Comment by drew-gross** [comment]
Can you post the current contents of your `_SCHEMA` collection and a curl that demonstrates the issue? Also make sure you are using the latest version of Parse Server (2.1.4)

**Comment by ntloc592** [comment]
I try to update System Schema via API
 - http://localhost:1337/schemas/_User - POST method

 - JSON data post
    {
             "_ApplicationId": "appId",
            "_ClientVersion": "browser",
            "_MasterKey": "masterKey",
           "_InstallationId": "308310ea-6516-75bb-bcf7-3c85fbf0ec2f",
           "_method": "PUT",
           "className": "_User",
           "fields": {
                "test_system": {
                     "type": "String"
                }
          }
    }

 - Result: 
   {
          "code": 136,
          "error": "field username cannot be added"
    }

=====================================================================

![image](https://cloud.githubusercontent.com/assets/6183747/13519492/de5229f4-e20a-11e5-875b-013df8b6f86e.png)

**Comment by ntloc592** [comment]
I make sure using lasted version 2.1.4

**Comment by Marco129** [comment]
Oh! My bad...
I assumed there will be a `_id` just like some of the test cases
Will provide bugfix asap

**Comment by ntloc592** [comment]
Thanks for this work!

**Comment by drew-gross** [comment]
Thanks for fixing the bug and adding tests @Marco129!
