### ISSUE TITLE
Run error after global install

### ISSUE THREAD

**Issue by xeoneux** [ParsePlatform/parse-server#947]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

`npm install -g parse-server`
`parse-server`

#### Logs/Trace

```
/usr/local/bin/parse-server: line 1: syntax error near unexpected token `"../lib/cli/parse-server"'
/usr/local/bin/parse-server: line 1: `require("../lib/cli/parse-server");'
```

**Comment by newstler** [comment]
have the same, node 5.8.0

**Comment by xeoneux** [comment]
Fixed through 78425c8 by @flovilmart

**Comment by newstler** [comment]
I just installed parse-server, isn't it in master yet? Because I still get this:
```
$ parse-server
/usr/local/bin/parse-server: line 1: syntax error near unexpected token `"../lib/cli/parse-server"'
/usr/local/bin/parse-server: line 1: `require("../lib/cli/parse-server");'
```

**Comment by xeoneux** [comment]
It's in the master but not in the release yet. Last release was earlier than mentioned commit.

**Comment by newstler** [comment]
Can you point me please how can I use it now?

**Comment by xeoneux** [comment]
Sure! You can manually add
```bash
#!/usr/bin/env node
```
in the top of file
`/usr/local/lib/node_modules/parse-server/bin/parse-server`

**Comment by newstler** [comment]
Thanks! Looks like it worked.

**Comment by LKrivtsov** [comment]
get this error on ubuntu 15.10 with latest version https://github.com/ParsePlatform/parse-server/releases/tag/2.1.5
node 5.7.1

**Comment by flovilmart** [comment]
Fixed with today's release 2.1.6
